# Generated by Django 4.2 on 2024-10-09 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='developing_program')),
                ('title', models.CharField(max_length=125)),
                ('title_uz', models.CharField(max_length=125, null=True)),
                ('title_ru', models.CharField(max_length=125, null=True)),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Developing Program',
                'verbose_name_plural': 'Developing Programs',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=125)),
                ('question_uz', models.CharField(max_length=125, null=True)),
                ('question_ru', models.CharField(max_length=125, null=True)),
                ('answer', models.CharField(max_length=255)),
                ('answer_uz', models.CharField(max_length=255, null=True)),
                ('answer_ru', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partners')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_uz', models.TextField(null=True)),
                ('message_ru', models.TextField(null=True)),
                ('full_name', models.CharField(max_length=125)),
                ('profession', models.CharField(max_length=125)),
                ('image', models.ImageField(upload_to='comment_student')),
            ],
            options={
                'verbose_name': 'Student Feedback',
                'verbose_name_plural': 'Student Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='why_us')),
                ('title', models.CharField(max_length=125)),
                ('title_uz', models.CharField(max_length=125, null=True)),
                ('title_ru', models.CharField(max_length=125, null=True)),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Why Us',
                'verbose_name_plural': 'Why Us',
            },
        ),
        migrations.CreateModel(
            name='DevelopingProgramDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('program_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='main_app.developingprogram')),
            ],
            options={
                'verbose_name': 'Program Detail',
                'verbose_name_plural': 'Program Details',
            },
        ),
    ]
