# Generated by Django 4.2 on 2024-10-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner'},
        ),
        migrations.AlterModelOptions(
            name='computercharacter',
            options={'verbose_name': 'ComputerCharacter'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Content'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='coursedetail',
            options={'verbose_name': 'CourseDetail'},
        ),
        migrations.AlterModelOptions(
            name='forwhomcourse',
            options={'verbose_name': 'forWhomCourse'},
        ),
        migrations.AlterModelOptions(
            name='mentorachievment',
            options={'verbose_name': 'MentorAchievment'},
        ),
        migrations.AlterModelOptions(
            name='mentorprofession',
            options={'verbose_name': 'MentorProfession'},
        ),
        migrations.AlterModelOptions(
            name='mentors',
            options={'verbose_name': 'Mentors'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Module'},
        ),
        migrations.AlterModelOptions(
            name='ordercourse',
            options={'verbose_name': 'OrderCourse'},
        ),
        migrations.AlterModelOptions(
            name='plancourse',
            options={'verbose_name': 'PlanCourse'},
        ),
        migrations.AddField(
            model_name='banner',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_uz',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='title_ru',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='title_uz',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title_ru',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title_uz',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='forwhomcourse',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='forwhomcourse',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='forwhomcourse',
            name='title_ru',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='forwhomcourse',
            name='title_uz',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='mentorachievment',
            name='title_ru',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='mentorachievment',
            name='title_uz',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofession',
            name='title_ru',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofession',
            name='title_uz',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='title_ru',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='title_uz',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='plancourse',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plancourse',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plancourse',
            name='half_time_ru',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='plancourse',
            name='half_time_uz',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='plancourse',
            name='title_ru',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='plancourse',
            name='title_uz',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='plancourse',
            name='total_month_ru',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='plancourse',
            name='total_month_uz',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
