# Generated by Django 4.2 on 2024-10-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_alter_banner_options_alter_computercharacter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedetail',
            options={'verbose_name': 'MentorAchievment'},
        ),
        migrations.AddField(
            model_name='plancourse',
            name='description_2',
            field=models.TextField(default=-2242),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plancourse',
            name='description_2_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plancourse',
            name='description_2_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plancourse',
            name='title_2',
            field=models.CharField(default=1, max_length=125),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plancourse',
            name='title_2_ru',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='plancourse',
            name='title_2_uz',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
