# Generated by Django 4.2 on 2024-10-05 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_alter_coursedetail_options_plancourse_description_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='courseAbout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.content'),
        ),
    ]
