# Generated by Django 4.2 on 2024-10-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_alter_coursedetail_courseabout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='content_category',
        ),
        migrations.AddField(
            model_name='module',
            name='content_category',
            field=models.ManyToManyField(related_name='modules', to='course_app.content'),
        ),
    ]
