# Generated by Django 4.2 on 2024-10-05 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_remove_module_content_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('title_uz', models.CharField(max_length=125, null=True)),
                ('title_ru', models.CharField(max_length=125, null=True)),
            ],
            options={
                'verbose_name': 'Lesson',
            },
        ),
        migrations.RemoveField(
            model_name='module',
            name='content_category',
        ),
        migrations.RemoveField(
            model_name='module',
            name='number',
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='courseAbout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.module'),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.AddField(
            model_name='lesson',
            name='module_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.module'),
        ),
    ]
