# Generated by Django 4.2 on 2024-10-05 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0006_lesson_remove_module_content_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedetail',
            options={'verbose_name': 'CourseDetail'},
        ),
        migrations.RemoveField(
            model_name='mentors',
            name='profession',
        ),
        migrations.AddField(
            model_name='mentorprofession',
            name='teacher_profession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='course_app.mentors'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course_app.module'),
        ),
    ]
