# Generated by Django 4.2 on 2024-10-05 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0007_alter_coursedetail_options_remove_mentors_profession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentors',
            name='achivement',
        ),
        migrations.AddField(
            model_name='mentorachievment',
            name='mentor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='course_app.mentors'),
            preserve_default=False,
        ),
    ]
