# Generated by Django 4.2 on 2024-10-05 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0008_remove_mentors_achivement_mentorachievment_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofession',
            name='teacher_profession',
        ),
        migrations.AddField(
            model_name='mentors',
            name='profession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='course_app.mentorprofession'),
            preserve_default=False,
        ),
    ]
