# Generated by Django 4.2 on 2024-10-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0009_remove_mentorprofession_teacher_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercourse',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
