# Generated by Django 4.2 on 2024-10-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0010_ordercourse_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors',
            name='position',
            field=models.CharField(default=1, max_length=125),
            preserve_default=False,
        ),
    ]
