# Generated by Django 4.2 on 2024-10-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0011_mentors_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors',
            name='position_ru',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='mentors',
            name='position_uz',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
