# Generated by Django 4.2 on 2024-10-05 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0012_mentors_position_ru_mentors_position_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetail',
            name='forWhom',
        ),
        migrations.AddField(
            model_name='forwhomcourse',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='forWhom', to='course_app.coursedetail'),
            preserve_default=False,
        ),
    ]
