# Generated by Django 4.2 on 2024-10-08 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0018_remove_forwhomcourse_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwhomcourse',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course_app.coursedetail'),
            preserve_default=False,
        ),
    ]
