# Generated by Django 4.2 on 2024-10-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0020_alter_forwhomcourse_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MentorAchievment',
            new_name='MentorAchievement',
        ),
        migrations.AlterModelOptions(
            name='computercharacter',
            options={'verbose_name': 'ComputerCharacter', 'verbose_name_plural': 'ComputerCharacters'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursedetail',
            options={'verbose_name': 'CourseDetail', 'verbose_name_plural': 'CourseDetails'},
        ),
        migrations.AlterModelOptions(
            name='courseplan',
            options={'verbose_name': 'CoursePlan', 'verbose_name_plural': 'CoursePlans'},
        ),
        migrations.AlterModelOptions(
            name='forwhomcourse',
            options={'verbose_name': 'ForWhomCourse', 'verbose_name_plural': 'ForWhomCourses'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='mentor',
            options={'verbose_name': 'Mentor', 'verbose_name_plural': 'Mentors'},
        ),
        migrations.AlterModelOptions(
            name='mentorachievement',
            options={'verbose_name': 'MentorAchievement', 'verbose_name_plural': 'MentorAchievements'},
        ),
        migrations.AlterModelOptions(
            name='mentorprofession',
            options={'verbose_name': 'MentorProfession', 'verbose_name_plural': 'MentorProfessions'},
        ),
        migrations.AlterModelOptions(
            name='mentorwork',
            options={'verbose_name': 'MentorWorkPlace', 'verbose_name_plural': 'MentorWorkPlaces'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.RenameField(
            model_name='computercharacter',
            old_name='protsetsor',
            new_name='processor',
        ),
        migrations.RenameField(
            model_name='computercharacter',
            old_name='video_cart',
            new_name='video_card',
        ),
        migrations.RenameField(
            model_name='coursedetail',
            old_name='computer_char',
            new_name='computer_character',
        ),
        migrations.RenameField(
            model_name='coursedetail',
            old_name='mentorDescription',
            new_name='mentor',
        ),
        migrations.RenameField(
            model_name='coursedetail',
            old_name='planCourse',
            new_name='plan_course',
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
